#########################################################################################################################################################
#
#  ███████╗██████╗░██████╗░░█████╗░░██╗░░░░░░░██╗███████╗██████╗░
#  ╚════██║██╔══██╗██╔══██╗██╔══██╗░██║░░██╗░░██║██╔════╝██╔══██╗
#  ░░███╔═╝██║░░██║██████╔╝███████║░╚██╗████╗██╔╝█████╗░░██████╔╝
#  ██╔══╝░░██║░░██║██╔══██╗██╔══██║░░████╔═████║░██╔══╝░░██╔══██╗
#  ███████╗██████╔╝██║░░██║██║░░██║░░╚██╔╝░╚██╔╝░███████╗██║░░██║
#  ╚══════╝╚═════╝░╚═╝░░╚═╝╚═╝░░╚═╝░░░╚═╝░░░╚═╝░░╚══════╝╚═╝░░╚═╝
#
# Commands and permissions:
# - /zdrawer » Main command (Alaises: /drawer) - zdrawer.use
# - /zdrawer reload » Reload config files - zdrawer.reload
# - /zdrawer craft » Craft commands - zdrawer.craft.use
# - /zdrawer give drawer <player> [<upgrade name>] [<material>] [<amount>] » Give a drawer - zdrawer.craft.drawer
# - /zdrawer give craft <player> [<craft name>] » Give a craft item - zdrawer.craft.craft
# - /zdrawer place <world name> <x> <y> <z> <block face> [<upgrade name>] [<material>] [<amount>] » Place a drawer - zdrawer.place
# - /zdrawer purge <world name> » Delete all the drawer in a specific world - zdrawer.purge
# - /zdrawer clear » Allows to remove all entities that come from the plugin. In case of a crash of your server or other it is possible that entities are duplicated. This command deletes them. - zdrawer.clear
#
#########################################################################################################################################################

drawer:
  limit: 2048
  item:
    material: BARREL
    name: "#22f54cᴅʀᴀᴡᴇʀ"
    lore:
      - "&8&oStore a large number of the same item"
      - ""
      - "#e3e3e3Content&8: #baffff%zdrawer_content%"
      - "#e3e3e3Amount&8: #baffff%zdrawer_amount%"
  craft:
    shade:
      - "ABA"
      - "BCB"
      - "ABA"
    ingredients:
      A:
        material: SPRUCE_WOOD
      B:
        material: SPRUCE_PLANKS
      C:
        material: CHEST
    # Allows you to change the investment details of the entities, do not touch it if you do not know how.
    # Even a small change can break the plugin display. Please be very careful.
  entitiesPosition:
    NORTH:
      itemDisplay:
        x: 0.5
        y: 0.5
        z: 1.01
        yaw: -180
        pitch: 0
      upgradeDisplay:
        x: 0.5
        y: 0.9
        z: 1.02
        yaw: -180
        pitch: 0
      textDisplay:
        x: 0.5
        y: 0.05
        z: 1.02
        yaw: 0
        pitch: 0
    EAST:
      itemDisplay:
        x: -0.01
        y: 0.5
        z: 0.5
        yaw: -90
        pitch: 0
      upgradeDisplay:
        x: -0.02
        y: 0.9
        z: 0.5
        yaw: -90
        pitch: 0
      textDisplay:
        x: -0.02
        y: 0.05
        z: 0.5
        yaw: 90
        pitch: 0
    SOUTH:
      itemDisplay:
        x: 0.5
        y: 0.5
        z: -0.01
        yaw: 0
        pitch: 0
      upgradeDisplay:
        x: 0.5
        y: 0.9
        z: -0.03
        yaw: 0
        pitch: 0
      textDisplay:
        x: 0.5
        y: 0.05
        z: -0.02
        yaw: 180
        pitch: 0
    WEST:
      itemDisplay:
        x: 1.01
        y: 0.5
        z: 0.5
        yaw: 90
        pitch: 0
      upgradeDisplay:
        x: -1.03
        y: 0.9
        z: 0.5
        yaw: 90
        pitch: 0
      textDisplay:
        x: 1.02
        y: 0.05
        z: 0.5
        yaw: -90
        pitch: 0
    UP:
      itemDisplay:
        x: 0.5
        y: -0.02
        z: 0.5
        yaw: 180
        pitch: -90
      upgradeDisplay:
        x: 0.5
        y: -0.03
        z: 0.9
        yaw: 180
        pitch: -90
      textDisplay:
        x: 0.5
        y: -0.03
        z: 0.05
        yaw: 0
        pitch: 90
    DOWN:
      itemDisplay:
        x: 0.5
        y: 1.01
        z: 0.5
        yaw: 180
        pitch: 90
      upgradeDisplay:
        x: 0.5
        y: 1.02
        z: 0.11
        yaw: 180
        pitch: 90
      textDisplay:
        x: 0.5
        y: 1.02
        z: 0.97
        yaw: 0
        pitch: -90

customCrafts:
  upgradeDisplay:
    result:
      url: "eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvOWQxNDlkYzRkNzFmOWE0N2I3MTRhZDgxN2YxNmYzYjU1N2QzMzUzZTBhZTNiY2M0ODExMmFlMmFjZDgyNyJ9fX0="
      name: "#54b2e8Upgrade Frame"
      lore:
        - "&8Upgrade frame for craft Drawer Upgrade"
    shade:
      - "AAA"
      - "BCB"
      - "AAA"
    ingredients:
      A:
        material: STICK
      B:
        material: SPRUCE_PLANKS
      C:
        material: BARREL

upgrades:
  woodUpgrade:
    displayItem:
      material: "IRON_BLOCK"
    limit: 4096
    craft:
      result:
        url: "eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvNmM3NjI4ZTg5N2NiNGM5MzEyZjgwMmYyOGMyZWM0NjZkN2U3MjFlYzM3MDEwMzc4Y2M0NWRkMmRjNjg4MTBjMyJ9fX0="
        name: "#cc7727Upgrade Wood"
      shade:
        - "AAA"
        - "BCB"
        - "AAA"
      ingredients:
        A:
          material: STICK
        B:
          material: BARREL
        C:
          customCraft: upgradeDisplay

numberFormat:
  enable: false
  formats:
    - format: ""
      maxAmount: 1000
    - format: "%.1fK"
      maxAmount: 1000000
    - format: "%.1fM"
      maxAmount: 1000000000
    - format: "%.1fB"
      maxAmount: 1000000000000
    - format: "%.2fT"
      maxAmount: 1000000000000000
    - format: "%.2fQ"
      maxAmount: 1000000000000000000