#########################################################################################################################################################
#
#  ███████╗██████╗░██████╗░░█████╗░░██╗░░░░░░░██╗███████╗██████╗░
#  ╚════██║██╔══██╗██╔══██╗██╔══██╗░██║░░██╗░░██║██╔════╝██╔══██╗
#  ░░███╔═╝██║░░██║██████╔╝███████║░╚██╗████╗██╔╝█████╗░░██████╔╝
#  ██╔══╝░░██║░░██║██╔══██╗██╔══██║░░████╔═████║░██╔══╝░░██╔══██╗
#  ███████╗██████╔╝██║░░██║██║░░██║░░╚██╔╝░╚██╔╝░███████╗██║░░██║
#  ╚══════╝╚═════╝░╚═╝░░╚═╝╚═╝░░╚═╝░░░╚═╝░░░╚═╝░░╚══════╝╚═╝░░╚═╝
#
# Commands and permissions:
# - /zdrawer » Main command (Alaises: /drawer) - zdrawer.use
# - /zdrawer reload » Reload config files - zdrawer.reload
# - /zdrawer give » Give commands - zdrawer.craft.use
# - /zdrawer give drawer <player> [<upgrade name>] [<material>] [<amount>] » Give a drawer - zdrawer.give.drawer
# - /zdrawer give craft <player> [<craft name>] » Give a craft item - zdrawer.give.craft
# - /zdrawer place <world name> <x> <y> <z> <block face> [<upgrade name>] [<material>] [<amount>] » Place a drawer - zdrawer.place
# - /zdrawer purge <world name> » Delete all the drawer in a specific world - zdrawer.purge
# - /zdrawer clear » Allows to remove all entities that come from the plugin. In case of a crash of your server or other it is possible that entities are duplicated. This command deletes them. - zdrawer.clear
#
# Placeholders
# - %zdrawer_content% » Displays the contents of the drawer with which the player interacts
# - %zdrawer_amount% » Displays the amount of the drawer with which the player interacts
# - %zdrawer_upgrade% » Displays the upgrade of the drawer with which the player interacts
#
# For item configuration, you can use the zMenu documentation: https://docs.zmenu.dev/configurations/items
#
#########################################################################################################################################################

enableDebug: true
enableDebugTime: false

drawer:
  limit: 2048 # The global limit for the number of items a single drawer can hold.

  # Drawer item, for item configuration, you can use the zMenu documentation: https://docs.zmenu.dev/configurations/items
  item:
    material: BARREL
    name: "#22f54cᴅʀᴀᴡᴇʀ"
    lore:
      - "&8&oStore a large number of the same item"
      - ""
      - "#e3e3e3Content&8: #baffff%zdrawer_content%"
      - "#e3e3e3Amount&8: #baffff%zdrawer_amount%"
      - "#e3e3e3Upgrade&8: #baffff%zdrawer_upgrade%"

  # Drawer craft
  craft:
    shade:
      - "ABA"
      - "BCB"
      - "ABA"
    ingredients:
      A:
        material: SPRUCE_WOOD
      B:
        material: SPRUCE_PLANKS
      C:
        material: CHEST

  # Allows you to change the investment details of the entities, do not touch it if you do not know how.
  # Even a small change can break the plugin display. Please be very careful.
  entitiesPosition:
    NORTH:
      itemDisplay: { x: 0.5, y: 0.5, z: 1.01, yaw: -180, pitch: 0 }
      upgradeDisplay: { x: 0.5, y: 0.9, z: 1.02,yaw: -180, pitch: 0 }
      textDisplay: { x: 0.5, y: 0.05, z: 1.02, yaw: 0, pitch: 0 }
    EAST:
      itemDisplay: { x: -0.01, y: 0.5, z: 0.5, yaw: -90, pitch: 0 }
      upgradeDisplay: { x: -0.02, y: 0.9, z: 0.5, yaw: -90, pitch: 0 }
      textDisplay: { x: -0.02, y: 0.05, z: 0.5, yaw: 90, pitch: 0 }
    SOUTH:
      itemDisplay: { x: 0.5, y: 0.5, z: -0.01, yaw: 0, pitch: 0 }
      upgradeDisplay: { x: 0.5, y: 0.9, z: -0.03, yaw: 0, pitch: 0 }
      textDisplay: { x: 0.5, y: 0.05, z: -0.02, yaw: 180, pitch: 0 }
    WEST:
      itemDisplay: { x: 1.01, y: 0.5, z: 0.5, yaw: 90, pitch: 0 }
      upgradeDisplay: { x: -1.03, y: 0.9, z: 0.5, yaw: 90, pitch: 0 }
      textDisplay: { x: 1.02, y: 0.05, z: 0.5, yaw: -90, pitch: 0 }
    UP:
      itemDisplay: { x: 0.5, y: -0.02, z: 0.5, yaw: 180, pitch: -90 }
      upgradeDisplay: { x: 0.5, y: -0.03, z: 0.9, yaw: 180, pitch: -90 }
      textDisplay: { x: 0.5, y: -0.03, z: 0.05, yaw: 0, pitch: 90 }
    DOWN:
      itemDisplay: { x: 0.5, y: 1.01, z: 0.5, yaw: 180, pitch: 90 }
      upgradeDisplay: { x: 0.5, y: 1.02, z: 0.11, yaw: 180, pitch: 90 }
      textDisplay: { x: 0.5, y: 1.02, z: 0.97, yaw: 0, pitch: -90 }

  # Defines the display sizes for item, upgrade, and text displays associated with the drawer.
  sizes:
    itemDisplay: { x: 0.6, y: 0.6, z: 0.01 } # Size for the item display.
    upgradeDisplay: { x: 0.15, y: 0.15, z: 0.01 } # Size for the upgrade display.
    textDisplay: { x: 0.6, y: 0.6, z: 0.6 } # Size for the text display

  # Tools to break a drawer
  breakMaterials:
    - WOODEN_AXE
    - STONE_AXE
    - IRON_AXE
    - GOLDEN_AXE
    - DIAMOND_AXE
    - NETHERITE_AXE

  blacklistMaterials:
    - BARREL
    - BEDROCK

# Custom crafts provided by the plugin, possibly for upgrades or special drawer-related items.
customCrafts:
  upgradeDisplay:
    # For item configuration, you can use the zMenu documentation: https://docs.zmenu.dev/configurations/items
    result:
      url: "eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvOWQxNDlkYzRkNzFmOWE0N2I3MTRhZDgxN2YxNmYzYjU1N2QzMzUzZTBhZTNiY2M0ODExMmFlMmFjZDgyNyJ9fX0="
      name: "#54b2e8Upgrade Frame"
      lore:
        - "&8Upgrade frame for craft Drawer Upgrade"
    shade:
      - "AAA"
      - "BCB"
      - "AAA"
    ingredients:
      A:
        material: STICK
      B:
        material: SPRUCE_PLANKS
      C:
        material: BARREL

# Upgrade configurations for drawers, defining various tiers or types of upgrades available.
upgrades:
  woodUpgrade:
    displayName: "Wood Upgrade" # Human-readable name for the upgrade.
    # Item used for display on drawer
    # For item configuration, you can use the zMenu documentation: https://docs.zmenu.dev/configurations/items
    displayItem:
      material: "IRON_BLOCK"
    limit: 4096 # New item limit when this upgrade is applied.
    # Craft for the upgrade
    craft:
      enable: true # Enable the craft
      # For item configuration, you can use the zMenu documentation: https://docs.zmenu.dev/configurations/items
      result:
        url: "eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvNmM3NjI4ZTg5N2NiNGM5MzEyZjgwMmYyOGMyZWM0NjZkN2U3MjFlYzM3MDEwMzc4Y2M0NWRkMmRjNjg4MTBjMyJ9fX0="
        name: "#cc7727Upgrade Wood"
      shade:
        - "AAA"
        - "BCB"
        - "AAA"
      ingredients:
        A:
          material: STICK
        B:
          material: BARREL
        C:
          customCraft: upgradeDisplay

# Number formatting settings for displaying large numbers in a more readable format.
numberFormat:
  # Toggle to enable/disable custom number formatting.
  enable: false
  # Documentation for String format: https://www.geeksforgeeks.org/java-string-format-method-with-examples/
  formats:
    - format: "" # Blank format to display text directly
      maxAmount: 1000
    - format: "%.1fK"
      maxAmount: 1000000
    - format: "%.1fM"
      maxAmount: 1000000000
    - format: "%.1fB"
      maxAmount: 1000000000000
    - format: "%.2fT"
      maxAmount: 1000000000000000
    - format: "%.2fQ"
      maxAmount: 1000000000000000000