name: zDrawer
author: Maxlego08
main: fr.maxlego08.zdrawer.DrawerPlugin
website: https://groupez.dev
description: Drawer Storage
version: ${project.version}
api-version: 1.20
depend:
  - zMenu
softdepend:
  - PlaceholderAPI
commands:
